### PR TITLE
Issue 41: added test for decode server message

### PR DESCRIPTION
**Pull request by maurelio1234**
It's a "smoke" test, assuming that small changes in the method inner algorithm will completely break decoding.

### CODE REVIEW

**Comment by maurelio1234** [comment]
test this please

**Comment by xcomponentadmin** [comment]
Can one of the admins verify this patch?

**Comment by nicolaserny** [comment]
fixes #41

**Comment by nicolaserny** [comment]
@maurelio1234 merge conflicts with your previous pull request (that I've just approved and merged)

**Pull request closed without merging**
