### PR TITLE
Issue #41: testing decode server message

### PR DESCRIPTION
**Pull request by maurelio1234**
fixes pull request #68

### CODE REVIEW

**Comment by xcomponentadmin** [comment]
Can one of the admins verify this patch?

**Comment by maurelio1234** [comment]
test this please

**Comment by nicolaserny** [comment]
add to whitelist

**Comment by maurelio1234** [comment]
??

**Comment by nicolaserny** [comment]
Jenkins GitHub pull request plugin works with a white list (people who can trigger builds).
I need to add you to the white list.
Now your pull requests can work fine with jenkins (I think)

**Comment by nicolaserny** [comment]
Closes #41

**Pull request merged**
